## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # family: "JetBrainsMono Nerd Font"
    family: "Iosevka Nerd Font Mono"
    #style: Regular

  # Bold font face
  bold:
    # family: "JetBrainsMono Nerd Font"
    family: "Iosevka Nerd Font Mono"
    # family: "Iosevka Nerd Font Complete Mono Bold"
    #style: Bold

  # Italic font face
  italic:
    # family: "JetBrainsMono Nerd Font"
    family: "Iosevka Nerd Font Mono"
    # family: "Iosevka Nerd Font Complete Mono Italic"
    #style: Italic

  # Bold italic font face
  bold_italic:
    # family: "JetBrainsMono Nerd Font"
    family: "Iosevka Nerd Font Mono"
    # family: "Iosevka Nerd Font Complete Mono Bold Italic"
    #style: Bold Italic

  # Point size
  size: 14

  # Offset
  #offset:
  #  x: 0
  #  y: 0

  # Glyph offset
  #glyph_offset:
  #  x: 0
  #  y: 0
