#!/bin/sh

#----------------PACMAN-----------------#
sudo pacman -S kitty alacritty fish neovim xclip brightnessctl feh rofi ttf-font-awesome git kcolorchooser neofetch htop lsd celluloid lxappearance-gtk3
chsh -s /usr/bin/fish

#----------------- GIT -------------------#
git clone https://gitlab.com/sharad777/dotfiles repo/dotfiles --depth 1
cp -r repo/dotfiles/config/* ~/.config/
git clone https://gitlab.com/sharad777/fonts repo/fonts --depth 1
git clone https://gitlab.com/sharad777/qtile repo/qtile --depth 1
cp -r repo/qtile/wallpaper ~/.wallpaper
git clone https://gitlab.com/sharad777/nvim ~/.config/nvim --depth 1
